version: '3.8'

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lakeSide_hotel_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - java-network

  backend:
    image: lakeside-hotel
    build:
      context: ./Server/
      dockerfile: Dockerfile
    ports:
      - "9192:9192"
    environment:
      SERVER_PORT: 9192
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lakeSide_hotel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE: 500KB
      SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE: 500KB
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      AUTH_TOKEN_EXPIRATIONINMILS: 3600000
      AUTH_TOKEN_JWTSECRET: "36763979244226452948404D635166546A576D5A7134743777217A25432A462D"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER: TRACE
    networks:
      - java-network
    depends_on:
      - db
      - frontend
    

  frontend:
    image: nginx:alpine
    build: 
      context: ./Client/
      dockerfile: Dockerfile
    ports:
      - "8089:80"
   

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - java-network


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - java-network
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    depends_on:
      - prometheus
    networks:
      - java-network
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8090:8080"
    networks:
      - java-network

  loki:
    image: grafana/loki:2.8.0
    ports:
      - '3100:3100'
    networks:
      - java-network
    

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yml:/etc/promtail/promtail.yml
    command: 
      - '--config.file=/etc/promtail/promtail.yml'
    networks:
      - java-network


  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - java-network
    depends_on:
      - prometheus 
networks:
  java-network:
    driver: bridge

volumes:
  db_data:
 
  grafana_data:
 