groups:
  - name: container_down_alerts
    rules:
      - alert: ContainerDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.instance }} is down"
          description: "Container on instance {{ $labels.instance }} has been down for more than 1 minute."