name: Docker Compose Test on GitAction

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Move to workdir
      run: cd /home/manish/DevOps_Practise/
      
    - name: Checkout repository
      uses: actions/checkout@v2
    

    - name: Build and push Docker image
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Check Container
      run: docker ps 
    - name: Hi
      run: echo 'Hello' 
