name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #   - name: Build and push client Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       context: ./Client
  #       push: true
  #       tags: manish181623/ci-cd_pipeline_client:latest
        
  #   - name: Build and push server Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       context: ./Server
  #       push: true
  #       tags: manish181623/ci-cd_pipeline_server:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd ${{ secrets.WORKDIR }}
          echo "Successfully entered into server"
          git pull origin master
          docker-compose up -d
        EOF
