name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push client Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Client
        push: true
        tags: manish181623/ci-cd_pipeline_client:latest
        
    - name: Build and push server Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Server
        push: true
        tags: manish181623/ci-cd_pipeline_server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_DNS }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /my_project
          sudo docker-compose pull
          sudo docker-compose pull
          sudo docker-compose up -d
