name: Docker Compose Test on GitAction

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: github-runner-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Check Container
      run: docker ps 
    - name: Hi
      run: echo 'Hello' 
